# Generated by Django 6.0 on 2025-12-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpmanager",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
