# Generated by Django 6.0 on 2025-12-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otp", "0002_otpmanager_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otpmanager",
            name="is_verified",
        ),
    ]
